# Scipy and Numpy Playground

This contains some scripts, functions, trials I ran on **scipy** and **numpy** overtime

In [5]:
###Imports
import numpy
import scipy

In [10]:
###Version Check
print(numpy.version.full_version)
print(scipy.version.full_version)

1.11.2
0.18.1


In [11]:
##Global Variables
start_list = range(10)

In [14]:
##Creating a numpy array
numpy_array = numpy.array(start_list)
numpy_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
###Checking numpy array dimension
numpy_array.ndim

1

In [20]:
###Checking numpy array shape
numpy_array.shape

(10,)

In [29]:
###Numpy array transformation
transformed_array = numpy_array.reshape((5,2))
transformed_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
##Indexing numpy array
transformed_array[1][0] =5

In [33]:
transformed_array

array([[0, 1],
       [5, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [35]:
numpy_array

array([0, 1, 5, 3, 4, 5, 6, 7, 8, 9])

In [43]:
##Operation Propagation
transformed_array*2
transformed_array[transformed_array>2] = 10

In [46]:
transformed_array.clip(0, 5)

array([[0, 1],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [49]:
transformed_array = [numpy.NAN,0, 5]

In [54]:
c = numpy.array([1, 2, numpy.NAN, 3, 4])

In [57]:
c[~numpy.isnan(c)]

array([ 1.,  2.,  3.,  4.])