In [ ]:
import pandas
import numpy
import math

In [ ]:
dataframe = pandas.read_csv('Prostate_Cancer.csv')

In [231]:
class KNN():
    def __init__(self,training_data, dataset, labels, k=None):
        self.training_data = training_data
        self.dataset = dataset
        self.labels = labels
        self.k = k if k else 3
        
    def classify(self):
        euclidean_distance = self.find_euclidean_distance()
        print(euclidean_distance)
        sort_distance = sorted(euclidean_distance)
        print('sorted distances')
        print(sort_distance)
        classCount={}          
        for i in range(self.k):
            voteIlabel =  self.labels[int(sort_distance[i])]
            classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1
            sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)
            return sortedClassCount

        
    def get_k(self):
        return math.sqrt(len(self.training_data))
    
    def find_euclidean_distance(self):
        data_size = self.dataset.shape[0]
        differences = numpy.tile(self.training_data, (data_size, 1)) - self.dataset
        euclidean_product = differences ** 2
        euclidean_sum = euclidean_product.sum(axis=1)
        distance = euclidean_sum ** 0.5
        print('distances')
        print(distance)
        return distance
    

a = KNN(training_data=[1, 0], dataset=numpy.array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]]), labels=['A','A','B','B'])
b = a.classify()

b

    

distances
[ 1.1         1.          1.          1.00498756]
[ 1.1         1.          1.          1.00498756]
sorted distances
[1.0, 1.0, 1.004987562112089, 1.1000000000000001]


[('A', 1)]

In [228]:
import operator
def classify0(inX, dataSet, labels, k):
    dataSetSize = dataSet.shape[0]
    diffMat = numpy.tile(inX, (dataSetSize,1)) - dataSet
    sqDiffMat = diffMat**2
    sqDistances = sqDiffMat.sum(axis=1)
    distances = sqDistances**0.5
    print('distances')
    print(distances)
    sortedDistIndicies = distances.argsort()    
    print('sorted distances')
    print(sortedDistIndicies)
    classCount={}          
    for i in range(k):
        voteIlabel = labels[sortedDistIndicies[i]]
        classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1
    sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)
    return sortedClassCount[0][0]

classify0([1, 0], dataSet=numpy.array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]]), labels=['A','A','B','B'], k=2)

distances
[ 1.1         1.          1.          1.00498756]
sorted distances
[1 2 3 0]


'A'

In [232]:
help(numpy.argsort)

Help on function argsort in module numpy.core.fromnumeric:

argsort(a, axis=-1, kind='quicksort', order=None)
    Returns the indices that would sort an array.
    
    Perform an indirect sort along the given axis using the algorithm specified
    by the `kind` keyword. It returns an array of indices of the same shape as
    `a` that index data along the given axis in sorted order.
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    axis : int or None, optional
        Axis along which to sort.  The default is -1 (the last axis). If None,
        the flattened array is used.
    kind : {'quicksort', 'mergesort', 'heapsort'}, optional
        Sorting algorithm.
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A single field can
        be specified as a string, and not all fields need be specified,
        but unspecified fields will still 

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
help(KNeighborsClassifier)